### ISSUE TITLE
linux脚本无法在arm7上使用

### ISSUE THREAD

**Issue by billy74** [cmliu/CFnat-Windows-GUI#12]
大佬 我是用的盒子刷机的linux，为什么用不了这个脚本啊 
系统如下：
系统版本 : Ubuntu 20.04.6 LTS  V20240201-4.4.35
armv7架构

脚本如下：
 状态: 已安装 未运行
 系统: Ubuntu
 架构: arm7
 IP类型: IPv4
 随机IP: TRUE
 数据中心: SJC,LAX,HKG
 有效延迟: 300ms
 转发端口: 443 TLS
 有效IP数: 10
 负载IP数: 10
 最大并发请求数: 100

选择测试运行后提示错误
请输入你的选择: 6
cfnat-linux-arm7: line 1: 无法获取文件，检查路径或TOKEN是否正确。: command not found
执行完成
按任意键返回

**Comment by cmliu** [comment]
漏写了一个v，已修复
