### ISSUE TITLE
Windows缩放比例大于等于125%情况下GUI界面显示不正常

### ISSUE THREAD

**Issue by Scott0902** [cmliu/CFnat-Windows-GUI#2]
我的Windows缩放比例是125%，运行GUI界面字体变大了，而按钮的位置没有相适应地作出调整，导致无法显示。
![capture1](https://github.com/user-attachments/assets/1da3cdfb-15e5-4ad7-bdfe-aa69250d6711)

**Comment by cmliu** [comment]
更新0.1.0.6试试，还是不行的话就双击“系统:”，就可以自由拖拽窗口了
