### ISSUE TITLE
CFnat.Windows.GUI.v0.1.0.8 最后执行报错

### ISSUE THREAD

**Issue by NONyou** [cmliu/CFnat-Windows-GUI#5]
杀毒软件关了，防火墙全关
最后运行报错
2024/10/18 17:13:14 无法监听 0.0.0.0:1234: listen tcp 0.0.0.0:1234: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by cmliu** [comment]
你的1234端口被占用了，换端口
