### ISSUE TITLE
电脑重启后，启动程序报错

### ISSUE THREAD

**Issue by medicandong** [cmliu/CFnat-Windows-GUI#6]
应用程序中发生了经处理的异常。如果兽击“继续”，应用程
序将忽略此错误并尝试维续。如课单击“退平”，应用程草将立
即关闭。
对路径“C:WIndo0Ws\,System32\cfnat.ini”的访i问被拒绝。

在windows目录下没有找到这个程序

**Comment by cmliu** [comment]
已修复，更新到v0.1.0.10版本试试
